### ISSUE TITLE
Add filter to manifest to define min sdk and target sdk

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#155]
Reference: http://developer.android.com/google/play/filters.html

The specifics will be defined in the following days

**Comment by adrianq** [comment]
- [ ] Add min sdk attribute to 4.1
- [ ] Check version 6.0 android

**Comment by ivanarrizabalaga** [comment]
@adrianq According to a couple of StackOverFlow questions (http://stackoverflow.com/questions/28174505/android-manifest-vs-gradle-script) the android manifest attributes are overriden by the build.gradle declaration.

Right now our *minSdkVersion*  is 15  (Android 4) instead of 16 (Android 4.1), I'm gonna change it.

In the other hand, I'm gonna try the app under an Android 6.0 emulator, if it goes fine should I move the targetSdkVersion too?
