### ISSUE TITLE
Library doesn't show the message "donwloading"

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1753]

**Comment by Amejia481** [comment]
I found what was the problem:
The app is only downloading the media files when the network is WIFI, but it is not showing to the user what's happening, and just shows a blank screen.

@ifoche @manuelplazaspalacio  is this the expected behavior? or do you want that I add an explanation message about why the files are not being downloaded?

When the app is cellular network:
![image](https://user-images.githubusercontent.com/773158/34915559-4606acd4-f8ff-11e7-96fc-e6f0a78346a9.png)

When the app is WIFI network
![image](https://user-images.githubusercontent.com/773158/34915568-64bf9b72-f8ff-11e7-91b9-64c2340370cf.png)

**Comment by Amejia481** [comment]
The expected behavior should be:

1) Active WiFi  + Downloaded videos: Videos are display
2) Inactive WiFi +  Downloaded videos: Videos are display
3) Active WiFi + Not downloaded videos: It shows the message "downloading..."
4) Inactive WiFi + Not downloaded videos: It shows the message "Media will only download..."
