### ISSUE TITLE
Suspected cases apparently wrong

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#187]

**Comment by ifoche** [comment]
The bug report is the following:
"We haven't noticed any new issues yet on this build, but we have noticed that the monitor module seems to be calculating items oddly for QIS_test_int. This is an existing issue instead of something that came out of the buddybuild update as it shows up on both the update and the Google Play version of the application. The two phones we are testing on have two different amounts of suspected cases under their monitor modules"

**Comment by ifoche** [comment]
​DHIS2 (counting blank and duplicate data)
        ​969
    BB Version of App
        603 (my phone) 
        ​609 (Panharith's phone)​
    Google Play Version
        565 (my phone)
        565 (Panharith's tablet)

**Comment by idelcano** [comment]
Problem 1:
The default max size of events (in program+orgunit) is set at 600.

The server contains more than 600 for the last six months, and we aren't pulling all the events.

@ifoche what do you suggest?
- increase the max size of events(temporal fix)
- pull all the events without paging(possible server problems).
- add method in the sdk to download all the events page by page(i think ivan tried it in the past. i'm not sure about this point).

Problem 2:
I have a different response between the Event capture and the api.
In the event capture (and in our pull without maxevent limit)  the number of events in total are 1142. But in the api are 2000.(I do filter the api query by program and orgunit)   

Problem 3:
Anyway, i need look the monitor code too, because the monitor stats are not correct. (For example, some days in the database not have events but in monitor yes ).

**Comment by ifoche** [comment]
Hi @idelcano . That's good news. In principle the number of events shouldn't be as high as it is now, because we're testing the app. Please, just for the testing (without uploading it to the server) can you setup the max number of events to 1000 or even more if needed and check whether or not the rest of the things are working?
For the API vs event capture mismatch... do you have any explanation? Have you identified which kind of events are not present in the event capture?

**Comment by idelcano** [comment]
> Please, just for the testing (without uploading it to the server) can you setup the max number of events to 1000 or even more if needed and check whether or not the rest of the things are working?
Ok.

I did it, and  the pull downloads the same number of events than the events number in "event capture".

But i find some bad numbers in the monitor table. for example, the day 29 not have events, but the table shown 12 events in total. I will analyse it.

> For the API vs event capture mismatch... do you have any explanation? Have you identified which kind of events are not present in the event capture?

Not at this moment. I need analyse it better.
Maybe... need i apply more filters to the query?
I will take a look of this after solve the first problem.

**Comment by idelcano** [comment]
The api and the event catpure have the same number of events :) . It was a problem with my query. The query: https://www.psi-mis.org/api/events?
program=IrppF3qERB7&orgUnit=Cj5E7dMNDoT&totalPages=true

**Comment by ifoche** [comment]
perfect, what about the testing with a high events threshold?

**Comment by idelcano** [comment]
Monitor:
I fix two bugs:
- Ignore a survey "from the future"(with dates like 2016-07-13).
- Change "days key" from "dd" to "yyyyMMdd". before that the "days key" gets values from other months.

Other thing:
-I added the wipe of the events before pull(like in malariapp).It is necessary to prevent bugs with a events not downloaded from the server but stored in the sdk db.


To rememmber:
If the events by program+orgunit are more than the maxEvents, the pull not download the last events.

@ifoche i will do PR, do you want more things like screenshots of the monitor chart and the query from the api with the number of the events?
