### ISSUE TITLE
Remove DHIS2 server URL

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/pictureapp#2250]
- [ ] Remove DHIS2 server URL setting
- [ ] Change url in login to https://apps.psi-mis.org
- [ ] Change login server settings from DHIS2 to Webservice

**Comment by idelcano** [comment]
@xurxodev

this task : 
"Remove DHIS2 server URL setting" is done in #2249 (but i only hide the DHIS2 server URL preference instead of remove it from the code, it is used in the main code). 

And the second task: "Change url in login to https://apps.psi-mis.org or remove EditText?"
that I have to do? Only change the default url to https://apps.psi-mis.org ?.
The default url is used by #2249 into new Program Configuration URL as default url.
