### ISSUE TITLE
Build workflow engine in separate thread

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2355]
When opening a new survey, screens are calculated with the workflow engine while a message is shown informing that screen is being prepared. That job could be moved to a separate thread started since dashboard is opened

**Comment by xurxodev** [comment]
@ifoche I have reviewed the current behaviour and It's this:

1 - NavigationController is built always from DashboardActivity using NavigationBuilder here:
[DashboardActivity](https://github.com/EyeSeeTea/pictureapp/blob/c48fbf01e48548abdaa4a690466d587cd96077f7/app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java#L800 )

2- if when SurveyFragment is opened the NavigationController is building then the SurveyFragment is subscribed to the end process with a listener here:
[SurveyFragment](https://github.com/EyeSeeTea/pictureapp/blob/c48fbf01e48548abdaa4a690466d587cd96077f7/app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java#L209)

3 - And the NavigationController build is realized in a separate thread always here:
[NavigationBuilder](https://github.com/EyeSeeTea/pictureapp/blob/c48fbf01e48548abdaa4a690466d587cd96077f7/app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationBuilder.java#L94)

I think the requirement of this issue is already being made.

**Comment by ifoche** [comment]
@xurxodev thanks for the analysis. That's good news :) . Let's move it to done, then
