### ISSUE TITLE
All 209 Pull scenarios producing a creation survey block

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2376]

**Comment by xurxodev** [comment]
@ifoche This occurs because when we are hacking push to return 209 error and we are not hacking pull to force pull. In 209 push canAddSurveys for the user is set to false and only during the pull process is set to true.
To test this.
Add code in eReferralsApiClient to return 2019
- In hasToUpdateMetadata method in MetadataConfigurationDBImporter class modify line 87 - to return true: } else if (true) {
- in PullDialogFragment modify pullSuccess method to dimis after delay:
  @Override
    public void pullSuccess() {
        Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                getDialog().dismiss();
            }
        }, 5000);
    }
