### ISSUE TITLE
In api/available calls, ignore additional keys being returned by the server without failing

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2445]

**Comment by xurxodev** [comment]
@ifoche The app is working with extra keys in api available and all web service endpoints because we have in the eReferralsAPIClient code:
``` Java
ObjectMapper objectMapper = new ObjectMapper()
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
```
Endpoints supported on this class:
* POST api -> push
* POST api/auth -> login
* POST api/searchActions -> to review Quarantine Surveys
* POST api/forgotpassword -> is not used currently
* GET api/available -> api available
