### ISSUE TITLE
Blanks on GPS coordinates and phone DEs

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#262]

**Comment by ifoche** [comment]
Some times we're receiving blanks on these DE. My guess is that, when we change the RDT answer, and removing recursively the values, we may be removing also the value for the GPS/phone metadata questions

**Comment by ifoche** [comment]
Confirmed, they're still happening

**Comment by idelcano** [comment]
@ifoche
i think it could be solved by the PR "repeated undefined surveys". I think
it because the location is stored in sharedpreferences by survey ID, and if
the android life-cycle restarts the application, this bug was changing the
survey id.

Anyway, i will take a look.

But, are you sure the phone question was removed before push?

is the problem the phone number question or  the phone metadata?.

Do you have any clue to how replicate this bug?
Thanks

**Comment by ifoche** [comment]
@idelcano that are good news. Then do not touch this issue, I will merge all the PRs and try after that, just in case. Answering your questions: 
- Yes, I'm sure, the user is submitting several surveys exactly in the same way, some of them have the phone, some don't. 
- The problem is the phone number, not the phone metadata
- For the moment I don't have any clue, but as I told you above, I'll merge the PRs and try to find out if it's still happening and if so, how can I reproduce it
