### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#3]
- [x] Implement cancel survey button. On click go back to the dashboard
- [x] Implement gallery mode (Move forward automatically when question answer)
- [x] Implement swipe feature. (Move to next image on swipe right and previous questions already answered)
- [x] Show finalize button on survey completed.
- [x] Show finalize button when the first question is answered ‘NO’. and disable all following questions
- [x] Show progress details (e.g. ‘3 of 8’)
- [x] When the finalize button is clicked change status to complete and get back to the dashboard

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers
Most of work is done, lots of details yet to be implemented but the core of the workflow is running pretty well.

A list of pending things:

- [ ] GridLayout, buttons with the right sized/position
- [ ] Images instead of labels in buttons
- [ ] A layout for Telephone question
- [ ] Review colors of the progress footer

**Comment by ivanarrizabalaga** [comment]
@adrianq I've just created a PR with a first set of features.
Yesterday I didnt manage to set a clean layout for the options or telephone but the flow is mostly done.
