### ISSUE TITLE
Check for duplicates before sending

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#421]

**Comment by ifoche** [comment]
As I told you on Friday, it finally seems that I was ok with my suspect of conflicts in the origin of this bug. Apparently, one of the sources of duplicates appears when you introduce "05" instead of "5" (for example) in the age question. This would be caused by a conflict (I'm just guessing but it looks like) as that DE doesn't reach the server and that survey is being resent forever. However there are also duplicates coming from negative surveys, so it's not the only source of duplicates. 

In this sense, this solution would imply 3 different strategies:
- [ ] Guess why the translation of 05 (or 01, 02, 03...) is producing a DV not compatible with a DHIS "Positive or Zero Integer", as it's configured server side (maybe just trunk the spaces before translating? but I strongly doubt that Java may be wrongly translating 05 into 5...)
- [ ] Avoid retrying conflicting surveys (and notify if we're not doing yet) on a conflict. That would avoid this problem (and hopefully also the rest)
- [ ] Check in the same places where we're checking for blanks (but specially when we're changing the "Time Sent" control DE to resend a survey) the content of the "Time Capture" control DE and in case it's exact with the last sent survey, just avoid sending that survey.

**Comment by idelcano** [comment]
First point: 
The positive integers 00-09 are conflict values in the server.{"object":"qQngeCbT4uI","value":"value_not_integer"}, and [0-9] are correct positive integers in the server. I fixed this truncating the value parsing it using Integer.parseInt before be saved as text.

Second point:
The surveys with conflict are saved as conflict survey, and a dialog inform to the user. The conflict surveys aren't resend  in the last version on development branch at least.

Third point:
The Controldataelement "time sent"(aBahytzj2u0) value is created and saved in the same line(new Date) I think it should be always new.
Did you looked duplicated surveys with the same sent time capture? 
If we have duplicates with same time sent i think the problem is outside of the conversion(maybe some events/surveys was not deleted from memory or db?).

Maybe we need use "time capture" qWMb2UM2ikL instead of "time sent", this date is set from survey completiondate.

Related suggestion: We can remove/check/ignore the surveys with duplicate creation date, this date should be unique always(as timestamp).
For example check if a survey have the same completion date than other, and remove the last one.
