### ISSUE TITLE
Check we're using time capture to setup event date

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#452]

**Comment by ifoche** [comment]
I think the only place we're setting the eventDate in a survey is [when translating from the SDK to our DB](https://github.com/EyeSeeTea/pictureapp/blob/8c2b1804f4d4e3cfcdb3265b7a1633bf8bd73ed9/app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java#L157-L157). People are worried about what would happen if someone runs out of airtime or network and get it back 5 days later. Are all the events going to have the same eventDate? I think so. @idelcano, do you remember if it had something to do with the PUT/POST problem? I thought it was only related to the creationDate. Why aren't we assigning event date? do you remember? However, if it can be done we should set the same time that is written in "Time Capture" DE, that if not bad, it's the completion date.

**Comment by idelcano** [comment]
@ifoche
> I think the only place we're setting the eventDate in a survey is when translating from the SDK to our 
DB. People are worried about what would happen if someone runs out of airtime or network and get it back 5 days later. Are all the events going to have the same eventDate? I think so. 

It only affects the control DataElement "time sent" date.

> @idelcano,  do you remember if it had something to do with the PUT/POST problem? I thought it was only related to the creationDate. 

The problem with the PUT/POST is only related with the event creation date(in the sdk DB).
we don't have that problem because we don't use it. (if a event have creation date, the push use Put instead of post)

>Why aren't we assigning event date? do you remember? However, if it can be done we should set the same time that is written in "Time Capture" DE, that if not bad, it's the completion date. 


The "event date" in a survey is sets in the survey constructor (with new date). It's like the creation date.
Do you want change it to CompletionDate?

For remember, we are setting the follow dates:

Push date ->Event  ControlDataElement: Time Sent (DATETIME_SENT_UID) New date on every push by survey.

Survey Creation date (set in the constructor of a survey as new Date)->It isn't used.

Survey Event Date( it's set in the constructor of a survey as new Date) -> Event Event Date

Survey Completion date -> Event ControlDataElement: Time capture (DATETIME_CAPTURE_UID)
