### ISSUE TITLE
Modify Dashboard

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/pictureapp#6]
Change the layout (columns of the dashboard):

- Date of completion
- RDT yes or no
- Sort of 'toString' based on answers

**Comment by ivanarrizabalaga** [comment]
![screenshot from 2015-07-20 14 28 31](https://cloud.githubusercontent.com/assets/6850223/8776804/b27f140e-2eeb-11e5-8265-a94a681456a4.png)

**Comment by adrianq** [comment]
@ivanarrizabalaga Good catch. I didn't realise the  +/- column was for the RDT column but obviously it makes all sense.

The big + will be used to push the pending surveys to DHIS.

As discussed, don't worry about the 'Status: no network' and 'Status: no wifi or 3G' for the moment. It will be sth to take care in Release II probably. Let's try to make the minimum changes because this was a tentative layout and it will probably be modified in future iterations.
