### ISSUE TITLE
Download Organisation from pull for treatment matrix

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/pictureapp#822]

**Comment by ifoche** [comment]
Just for the record. The way partners (Organisations) are stored in the DHIS model is as follows:
- Volunteers. Each volunteer has an equivalent Category Option, which code field is exactly the username.
- Partners. The partners are stored as a CategoryOptionGroupSet. Concretely [this one](https://dev.scpr-mm-mal.org/api/categoryOptionGroupSets/yVH67wmhryq). So that UID (yVH67wmhryq) can be hardcoded and from now calling to that query will retrieve all the partners configured in the system. If we iterate on all the CategoryOptionGroups contained in that CategoryOptionGroupSet, we would get (by now) the following Partners:
   - [Matrix](https://dev.scpr-mm-mal.org/api/categoryOptionGroups/ZC8VhcjUVIT)
   - [IOM](https://dev.scpr-mm-mal.org/api/categoryOptionGroups/QQydPK1L24f)

Once we get the partners (CategoryOptionGroups), we just need to loop on all the CategoryOptions inside each CategoryOptionGroup, to look for the UID of the CategoryOption of our user, in order to get which organisation (partner) we belong to, and link our user in our DB to that organisation. That way, each time we want to get a treatment, we could pass also the organisation we belong to, to retrieve the appropriate treatment for us.

**Comment by xurxodev** [comment]
For avoid create many tables with this request download CategoryOptionGroup filter by CategoryOptionGroupSet and CategoryOption
https://dev.scpr-mm-mal.org/api/categoryOptionGroups?filter=categoryOptionGroupSet.id:eq:yVH67wmhryq&filter=categoryOptions.id:eq:nTrd5CQKjxd
