### ISSUE TITLE
Add ou description when closing ou

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#93]
Append to OU description: [Next Line][Next Line] Android Surveillance App set the closing date to dd mmm yyyy because over 30 surveys were pushed within 1 hour.

**Comment by idelcano** [comment]
I was append the "Android Surveillance App set the closing date to dd mmm yyyy because over 30 surveys were pushed within 1 hour." in the end of the description. 
But i am not sure about how save /n next line in JSON. 

I understand this is the good description:
"Actual description"
next line 
next line
"Android Surveillance App set the closing date to dd mmm yyyy because over 30 surveys were pushed within 1 hour."

Now:
"Actual description" "Android Surveillance App set the closing date to dd mmm yyyy because over 30 surveys were pushed within 1 hour."
Or:
Actual description /n/n Android Surveillance App set the closing date to dd mmm yyyy because over 30 surveys were pushed within 1 hour.

it´s right now?
